export const AREAS_LIST = [
  "Administração e Serviços",
  "Águas",
  "Almoxarifado Central",
  "Almoxarifado NAF",
  "Ativos Patrimoniais",
  "Biomassa",
  "Caustificação e Forno",
  "Caldeira de Recuperação e Evaporação",
  "Central Circular",
  "Centro de Treinamento Industrial",
  "Comunicação",
  "Confiabilidade",
  "Conservação e Jardinagem",
  "Confiabilidade e Sistemas Industriais",
  "Controladoria",
  "Energia",
  "Engenheira de Processos",
  "Engenharia de Projetos",
  "Financeiro",
  "Fiscal",
  "Gerência Geral",
  "Gestão de Biomassa",
  "Integridade",
  "Inovação e Tecnologia",
  "Jurídico",
  "Laboratório Qualidade Industrial",
  "Laboratório Qualidade da Madeira",
  "Linha de Fibras",
  "Logística de Celulose",
  "Manutenção Automação",
  "Manutenção Eletríca",
  "Manutenção Instrumentação",
  "Manutenção Máquinas Móveis",
  "Manutenção Mecânica",
  "Manutenção Oficina",
  "Manutenção Complementar",
  "Planejamento",
  "Preparo de Cavaco",
  "Processos Industriais",
  "Recebimento de Madeira",
  "Resíduos Sólidos Industriais",
  "Restaurante Industrial",
  "Saúde Ocupacional",
  "Secagem e Enfardamento",
  "Segurança Patrimonial e Limpeza Predial",
  "Segurança do Trabalho",
  "SEPRE",
  "Serviços Administrativos",
  "Suprimentos",
  "Sustentabilidade",
  "Tecnologia da informação",
  "Outra"
];
